apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-assembly 
  labels:
    name: nfs-pv-assembly
spec:
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  capacity:
      storage: 1Gi
  nfs:
    path: /assembly
    server: NFS_IP 
