kind: Service
apiVersion: v1
metadata:
  name: spark-webui-worker
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 32081
  selector:
    component: spark-worker
