kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-master-controller
spec:
  replicas: 1
  selector:
    component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: gcr.io/google_containers/spark:1.5.2_v1
          imagePullPolicy:  IfNotPresent
          command: ["/start-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
          volumeMounts:
            - mountPath: /mnt
              name: casefiles 
      volumes:
        - name: assembly
          persistentVolumeClaim:
            claimName: assembly 
        - name: casefiles
          persistentVolumeClaim:
            claimName: nfs-root 

