apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pv-provisioning-1
  labels:
    name: kafka-pv-provisioning-1
  annotations:
    volume.alpha.kubernetes.io/storage-class: any
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 62Gi 
