apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        resources:
            requests:
              memory: "6500Mi"
              cpu: "1500m"
        securityContext:
          privileged: true
        volumeMounts:
          - name: disk-blocks 
            mountPath: /exports
          - name: assembly
            mountPath: /exports/assembly
      volumes:
        - name: disk-blocks
          persistentVolumeClaim:
            claimName: nfs-pv-provisioning-disk-blocks 
        - name: assembly 
          persistentVolumeClaim:
            claimName: nfs-pv-provisioning-assembly
