kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: assembly
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: "nfs-pv-assembly"
