kind: Service
apiVersion: v1
metadata:
  name: nfs-server
spec:
  type: NodePort 
  ports:
    - name: nfs
      port: 2049
      nodePort: 32049
    - name: mountd
      port: 20048
      nodePort: 32048
    - name: rpcbind
      port: 111
      nodePort: 32111
  selector:
    role: nfs-server
