apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-provisioning-disk-blocks
  labels:
    name: nfs-pv-provisioning-disk-blocks
  annotations:
    volume.alpha.kubernetes.io/storage-class: any
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 251Gi 
